### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [Crescent-Labs/iqra-android#14]
Would you consider publishing the `.apk` here at Github – for those without Playstore access? Thanks in advance!

**Comment by mmmoussa** [comment]
Another release is coming soon. For the next release and those that follow I will include the latest released .apk in this project's repo.

**Comment by IzzySoft** [comment]
Thanks! Looking forward to that. Once available, please let me know (e.g. by closing this issue :)

**Comment by IzzySoft** [comment]
Thanks for including the *code* of the release! But is it just me, or did you forget the `.apk` this issue asked about? ;) Pointer: [Creating releases](https://help.github.com/articles/creating-releases/).

**Comment by mmmoussa** [comment]
The APK was not forgotten, but I had included it directly in the repo with a reference to it in the README as opposed to including it on the release page. It is now also available from the release page.

**Comment by IzzySoft** [comment]
Thanks! Now I've found both copies :) Be welcome to point other "Google abstinent people" [to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.mmmoussa.iqra), where they now can install your app using the F-Droid client – and stay up-to-date. Thanks to your adding the APK to `releases/`, new releases `.apk` files should be available via my repo within 24h, and the users will receive an update notice automatically. Just create a tag and attach the file as described (and as you did), all else then will happen automatically.

Thanks again!
